name: CI - Test & Lint & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_DB: glrchain
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint (non-fatal)
        run: |
          pip install flake8 || true
          flake8 || true

      - name: Run tests (placeholder)
        run: |
          echo "No tests configured — add tests to run here"

      - name: Build Docker image (CI only, not pushed)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: glrchain/backend:ci-${{ github.sha }}
